import Head from "next/head";
import Link from "next/link";

const links = ["state-batching"];

export default function Home() {
  return (
    <>
      <Head>
        <title>React Research</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {links.sort().map((link) => (
          <Link key={link} href={`/experiments/${link}`}>
            {link}
          </Link>
        ))}
      </main>
    </>
  );
}
